
module.exports = {
	"0": "Successfully completed.",
	"1": "Session with this number already exists.",
	"2": "Invalid Dealer code.",
	"3": "Invalid acceptance outlet code.",
	"4": "Invalid Operator code.",
	"5": "Invalid session code format.",
	"6": "Either key / password is wrong OR key expired",
	"7": "Invalid denomination. Please try with valid denomination.",
	"8": "Invalid number format",
	"9": "Incorrect format of account number",
	"10": "Invalid request message format.",
	"11": "Session with such a number does not exist.",
	"12": "The request is made from an unregistered IP.",
	"13": "The outlet is not registered by operator",
	"15": "Operator is not supported",
	"17": "The phone number does not match the previously entered number.",
	"18": "The payment amount does not match the previously entered amount.",
	"19": "The account number does not match the previously entered number.",
	"20": "The payment is being completed.",
	"21": "Dealer wallet balance exhausted",
	"22": "Not enough wallet balance, blocked wallet etc.",
	"23": "Invalid Mobile Number. Make sure your number belongs to this provider.",
	"24": "Error of connection with the provider’s server or a routine break in CyberPlat®."
}
