
module.exports = {
	"0": "Successfully completed.",
	"1": "Session with this number already exists.",
	"2": "Invalid Dealer code.",
	"3": "Invalid acceptance outlet code.",
	"4": "Invalid Operator code.",
	"5": "Invalid session code format.",
	"6": "Either key / password is wrong OR key expired",
	"7": "Invalid denomination. Please try with valid denomination.",
	"8": "Invalid number format",
	"9": "Incorrect format of account number",
	"10": "Invalid request message format.",
	"11": "Session with such a number does not exist.",
	"12": "The request is made from an unregistered IP.",
	"13": "The outlet is not registered by operator",
	"15": "Operator is not supported",
	"17": "The phone number does not match the previously entered number.",
	"18": "The payment amount does not match the previously entered amount.",
	"19": "The account number does not match the previously entered number.",
	"20": "The payment is being completed.",
	"21": "Dealer wallet balance exhausted",
	"22": "Not enough wallet balance, blocked wallet etc.",
	"23": "Invalid Mobile Number. Make sure your number belongs to this provider.",
	"24": "Error of connection with the provider’s server or a routine break in CyberPlat®.",
	"25": "The operator is temporary blocked",
	"26": "Dealer is temporary blocked",
	"27": "The account is temporary blocked",
	"30": "System Error",
	"31": "Exceeded number of simultaneously processed requests.",
	"32": "There should be time gap of 60 min for duplicate transactions with same number.",
	"33": "This denomination is applicable in <Flexi OR Special> category",
	"34": "Transaction ID is not found",
	"35": "Cannot change status of transaction",
	"36": "Required transaction is already in process",
	"37": "An attempt of referring to the gateway that is different from the gateway at the previous",
	"38": "nvalid transaction date",
	"39": "Invalid account number.",
	"40": "PIN-card is not registered",
	"41": "Error in saving the payment in the system.",
	"42": "Error in saving the receipt to the database.",
	"43": "Session is expired. Try to start new session",
	"44": "Client cannot work at this server",
	"45": "Specific operator not activated for dealer",
	"46": "Cannot complete a failed transaction",
	"47": "Attempt to pay not in working hours",
	"48": "Error in saving the session data to the database.",
	"50": " System is temporary out of service",
	"51": "Details are not found in database",
	"52": "Dealer may be blocked",
	"53": "Outlet may be blocked",
	"54": "User (cashier) may be blocked",
	"55": "nvalid type of dealer",
	"56": "Invalid type of outlet",
	"57": "Invalid type of user (cashier)",
	"81": "Exceeded the max payment amount (if you set the overall amount limit in dealer cabinet portal)",
	"82": "Daily debit amount has been exceeded.",
	"83": "Maximum payment amount for the outlet has been exceeded.",
	"84": "Daily total amount for the outlet has been exceeded",
	"85": "AMOUNT ALL is invalid",
	"86": "Invalid rate value",
	"87": "Beneficiary is blocked",
	"88": "Duplicate Transaction (Same Mobile Number)",
	"89": "A limit by a beneficiary is reached",
	"134": "Make sure using Production Keys",
	"137": "Make sure using Production Keys and Correct Password",
	"224": "Operator system is down. Please try again later.",
	"333": "Unknown error from Provider side",
	"171": " Manually Cancelled"
}
